version: "3.8"

services:
  # Go 后端服务
  go-admin:
    build: .
    container_name: go-admin-prod
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      # 数据库配置 - 连接外部MySQL
      DB_HOST: ${DB_HOST:-mysql-server}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-shgytywe!#%65926328}
      DB_NAME: ${DB_NAME:-go_admin}
      # Redis 配置 - 连接外部Redis
      REDIS_HOST: ${REDIS_HOST:-redis-server}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-Test!#$1234.hjdgsag}
      # JWT 配置
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      # 服务器配置
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8081
      GIN_MODE: release
    volumes:
      - ./uploads:/app/uploads # 持久化上传目录
    networks:
      - db-network # 连接到数据库网络

networks:
  db-network:
    external: true # 使用外部网络，由deploy-db.sh创建
