services:
  # MySQL 数据库（仅用于本地开发，生产环境使用独立部署的容器）
  mysql:
    image: mysql:8.0
    container_name: go-admin-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_DATABASE: go_admin
      MYSQL_USER: go_admin
      MYSQL_PASSWORD: go_admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - go-admin-network
    profiles:
      - local # 仅用于本地开发

  # Redis 服务（仅用于本地开发，生产环境使用独立部署的容器）
  redis:
    image: redis:7-alpine
    container_name: go-admin-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    networks:
      - go-admin-network
    profiles:
      - local # 仅用于本地开发

  # Go 后端服务（生产环境 - 连接现有数据库容器）
  go-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_PROGRESS: plain
    container_name: go-admin-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      # 数据库配置 - 连接现有容器
      DB_HOST: ${DB_HOST:-mysql57}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-shgytywe!#%65926328}
      DB_NAME: ${DB_NAME:-go_admin}
      # Redis 配置 - 连接现有容器
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-Test!#$1234.hjdgsag}
      # JWT 配置
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      # 服务器配置
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8081
      GIN_MODE: ${GIN_MODE:-release}
    volumes:
      - ./uploads:/app/uploads # 持久化上传目录
    network_mode: "host" # 使用host网络模式，直接连接本地端口
    profiles:
      - prod # 生产环境只启动Go服务

  # Go 后端服务（开发环境 - 连接本地数据库）
  go-admin-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-admin-api-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      # 数据库配置 - 连接本地数据库
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-go_admin}
      # Redis 配置 - 连接本地Redis
      REDIS_HOST: ${REDIS_HOST:-host.docker.internal}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      # JWT 配置
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      # 服务器配置
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8081
      GIN_MODE: ${GIN_MODE:-debug}
    volumes:
      - ./uploads:/app/uploads # 持久化上传目录
    networks:
      - go-admin-network
    profiles:
      - dev # 开发环境不依赖其他服务

volumes:
  mysql_data:
  redis_data:

networks:
  go-admin-network:
    driver: bridge
