# 生产环境Docker Compose配置
# 只包含后端API服务，MySQL和Redis使用外部容器

services:
  # Go 后端服务
  go-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-admin-api
    ports:
      - "8081:8081"
    environment:
      - TZ=UTC
      # 数据库配置 - 连接现有容器
      - DB_HOST=mysql57
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=shgytywe!#%65926328
      - DB_NAME=go_admin
      # Redis 配置 - 连接现有容器
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Test!#$1234.hjdgsag
      # JWT 配置
      - JWT_SECRET=your-secret-key-change-in-production
      # 服务器配置
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
      - GIN_MODE=release
    volumes:
      - uploads_data:/app/uploads
      - /etc/localtime:/etc/localtime:ro
    networks:
      - db-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

volumes:
  uploads_data: # 文件上传存储卷
    driver: local

networks:
  db-network:
    external: true
